clear_all_shortcuts yes
kitty_mod ctrl+shift


# Meta
map kitty_mod+tab command_palette

# Copy Paste
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_to_clipboard
# map ctrl+shift+o pass_selection_to_program
map ctrl+INSERT copy_to_buffer a
map shift+INSERT paste_from_buffer a

# Font Size
map ctrl+equal change_font_size all +2.0
map kitty_mod+equal change_font_size all *2.0

map ctrl+minus change_font_size all -2.0
map kitty_mod+minus change_font_size all /2.0

map ctrl+0 change_font_size all 0

# Global Window Keys
map kitty_mod+l neighboring_window right
map kitty_mod+h neighboring_window left
map kitty_mod+j neighboring_window down
map kitty_mod+k neighboring_window up
map kitty_mod+c close_window
map kitty_mod+ENTER new_window_with_cwd

# Window Mode
map --new-mode wm --on-unknown end kitty_mod+w

map --mode wm t combine      : pop_keyboard_mode     : push_keyboard_mode tm
map --mode wm r combine      : start_resizing_window : pop_keyboard_mode
map --mode wm ctrl+w combine : detach_window         : pop_keyboard_mode

map --mode wm r next_layout
map --mode wm s goto_layout vertical
map --mode wm e goto_layout horizontal
map --mode wm i toggle_layout
map --mode wm ctrl+o close_other_windows_in_tab

map --mode wm ctrl+l move_window right
map --mode wm ctrl+h move_window left
map --mode wm ctrl+j move_window down
map --mode wm ctrl+k move_window up
map --mode wm ctrl+f move_window_forward

map --mode wm l neighboring_window right
map --mode wm h neighboring_window left
map --mode wm j neighboring_window down
map --mode wm k neighboring_window up

map --mode wm left resize_window narrower
map --mode wm right resize_window wider
map --mode wm up resize_window taller
map --mode wm down resize_window shorter
map --mode wm home resize_window reset

map --mode wm ] next_window
map --mode wm [ previous_window

map --mode wm c close_window

# Tabs
map --new-mode tm --on-unknown end kitty_mod+t

map --mode tm w combine : pop_keyboard_mode : push_keyboard_mode wm

map --mode tm t       combine  : new_tab                       : pop_keyboard_mode
map --mode tm ctrl+w  combine  : detach_tab                    : pop_keyboard_mode
map --mode tm r       combine  : set_tab_title                 : pop_keyboard_mode
map --mode ctrl+o     combine  : close_other_tabs_in_os_window : pop_keyboard_mode

map --mode tm shift+h move_tab_backward
map --mode tm shift+l move_tab_forward

map --mode tm l next_tab
map --mode tm h previous_tab
map --mode tm ] next_tab
map --mode tm [ previous_tab

map --mode tm c close_tab

# Scrolling
map ctrl+g scroll_home
map ctrl+shift+g scroll_end

map ctrl+shift+up scroll_line_up
map ctrl+shift+down scroll_line_down

map ctrl+shift+page_up scroll_page_up
map ctrl+shift+page_down scroll_page_down
map ctrl+shift+u scroll_page_up
map ctrl+shift+d scroll_page_down

map ctrl+shift+x scroll_to_prompt 1
map ctrl+shift+z scroll_to_prompt -1

map ctrl+shift+/ search_scrollback
