# https://wiki.hypr.land/Configuring/

source = ~/.cache/wal/colors-hyprland.conf

source = ~/.config/hypr/hypr_keyword.conf
source = ~/.config/hypr/hypr_execOnce.conf
source = ~/.config/hypr/hypr_env.conf
source = ~/.config/hypr/hypr_permissions.conf

source = ~/.config/hypr/hypr_monitor.conf
source = ~/.config/hypr/hypr_workspaceRules.conf
source = ~/.config/hypr/hypr_windowRules.conf
source = ~/.config/hypr/hypr_visuals.conf

source = ~/.config/hypr/hypr_input.conf
source = ~/.config/hypr/hypr_keybindings.conf
