# sample hyprlock.conf
# for more configuration options, refer https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock
#
# rendered text in all widgets supports pango markup (e.g. <b> or <i> tags)
# ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#general-remarks
#
# shortcuts to clear password buffer: ESC, Ctrl+U, Ctrl+Backspace
#
# you can get started by copying this config to ~/.config/hypr/hyprlock.conf
#

#test
$font = Monospace

general {
    hide_cursor = false
    ignore_empty_input = true
    fail_timeout = 900
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    bezier = overshoot, 0.05, 0.9, 0.1, 1.1
    animation = fadeIn, 1, 1, linear
    animation = fadeOut, 1, 4, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
}

input-field {
    monitor =
    size = 15%, 3%
    outline_thickness = 2
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    outer_color = rgb(86,100,154) rgb(103,107,152) 45deg
    check_color = rgb(199,198,203) rgb(107,102,125) 120deg
    fail_color = rgb(33,28,49) rgb(33,28,49) 90deg
    numlock_color = rgb(118,157,192) rgb(199,198,203) 45deg
    capslock_color = rgb(91,109,166) rgb(99,121,173) 90deg

    invert_numlock = true
    font_color = rgb(110,142,182)
    fade_on_empty = true
    fade_timeout = 0
    rounding = 15

    font_family = $font
    placeholder_text =
    fail_text = "$PAMFAIL"

    # uncomment to use a letter instead of a dot to indicate the typed password
    dots_text_format = *
    dots_size = 0.3
    dots_spacing = 0.2

    position = 0, 300
    halign = center
    valign = bottom
}

# TIME
label {
    monitor =
    text = $TIME # ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#variable-substitution
    font_size = 90
    font_family = $font
    color = rgb(110,142,182)

    position = -30, -200
    halign = center
    valign = top
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y" # update every 60 seconds
    font_size = 25
    font_family = $font
    color = rgb(110,142,182)

    position = -30, -350
    halign = center
    valign = top
}
