

[tempo]
weather_location = { City = "Derby" }
formats = [ "%H:%M", "%v %H:%M" ]
weather_indicator = "IconAndTemperature"

[settings]
battery_format = "Icon"
peripheral_battery_format = "IconAndTime"
audio_indicator_format = "IconAndPercentage"
microphone_indicator_format = "IconAndPercentage"
indicators = [ "Audio", "Microphone" ]

[system_info]
indicators = ["Cpu", "Memory", "Temperature" ]
interval = 5

[system_info.cpu]
warn_threshold = 60
alert_threshold = 85

[system_info.memory]
warn_threshold = 70
alert_threshold = 85

[system_info.temperature]
warn_threshold = 60
alert_threshold = 80
sensor = "acpitz temp1"

[workspaces]
group_by_monitor = true
enable_workspace_filling = true
max_workspaces = 10

[[CustomModule]]
name = "GPU_Info"
type = "Button"
command = "kitty nvtop"
listen_cmd = "fish -c 'while true; gpu_status; sleep 5; end'"

[[CustomModule]]
name = "CPU_Info"
type = "Button"
command = "kitty btop"
listen_cmd = "fish -c 'while true; cpu_status; sleep 5; end'"

[[CustomModule]]
name = "RAM_Info"
type = "Button"
command = "fish -c 'waypaper --wallpaper /home/drspliff/Pictures/random/pepe_has_no_ram.gif; sleep 5; waypaper --random'"
listen_cmd = "fish -c 'while true; ram_status; sleep 5; end'"


[modules]
left = [ "Tempo", "WindowTitle" ]
center = [ "Workspaces" ]
right = [ "MediaPlayer", [ "CPU_Info", "GPU_Info", "RAM_Info", "Settings"] ]


