[tempo]
weather_location = { City = "Derby" }
weather_indicator = "Icon"

[settings]
battery_format = "Icon"
peripheral_battery_format = "IconAndTime"
audio_indicator_format = "IconAndPercentage"
microphone_indicator_format = "IconAndPercentage"
indicators = [ "Audio", "Microphone" ]

[system_info]
indicators = ["Cpu", "Memory", "Temperature" ]
interval = 5

[system_info.cpu]
warn_threshold = 60
alert_threshold = 85

[system_info.memory]
warn_threshold = 70
alert_threshold = 85

[system_info.temperature]
warn_threshold = 60
alert_threshold = 80
sensor = "acpitz temp1"

[[CustomModule]]
name = "MyClock"
type = "Text"
listen_cmd = "sh -c 'while true; do echo \"{\\\"text\\\": \\\"$(date +\"%H:%M\")\\\", \\\"alt\\\": \\\"\\\"}\"; sleep 1; done'"

[modules]
left = [ "Workspaces" ]
center = [ "MyClock" ]
right = [ [ "WindowTitle", "MediaPlayer", "SystemInfo", "Settings", "Tempo"] ]


