[tempo]
weather_location = { City = "Derby" }
formats = [ "%H:%M", "%v %H:%M" ]
weather_indicator = "IconAndTemperature"

[settings]
battery_format = "Icon"
peripheral_battery_format = "IconAndTime"
audio_indicator_format = "IconAndPercentage"
microphone_indicator_format = "IconAndPercentage"
indicators = [ "Audio", "Microphone" ]

[system_info]
indicators = ["Cpu", "Memory", "Temperature" ]
interval = 5

[system_info.cpu]
warn_threshold = 60
alert_threshold = 85

[system_info.memory]
warn_threshold = 70
alert_threshold = 85

[system_info.temperature]
warn_threshold = 60
alert_threshold = 80
sensor = "acpitz temp1"

[[CustomModule]]
name = "GPU_Info"
type = "Button"
command = "kitty nvtop"
listen_cmd = "fish -c 'while true; gpu_status; sleep 5; end'"

[modules]
left = [ "Workspaces" ]
center = [ "Tempo" ]
right = [ [ "WindowTitle", "MediaPlayer", "GPU_Info", "SystemInfo", "Settings"] ]


