$background_a = {background.strip}ed
$foreground_a = {foreground.strip}ed
$color0_a = {color0.strip}ed
$color1_a = {color1.strip}ed
$color2_a = {color2.strip}ed
$color3_a = {color3.strip}ed
$color4_a = {color4.strip}ed
$color5_a = {color5.strip}ed
$color6_a = {color6.strip}ed
$color7_a = {color7.strip}ed
$color8_a = {color8.strip}ed
$color9_a = {color9.strip}ed
$color10_a = {color10.strip}ed
$color11_a = {color11.strip}ed
$color12_a = {color12.strip}ed
$color13_a = {color13.strip}ed
$color14_a = {color14.strip}ed
$color15_a = {color15.strip}ed
