hl.env("LIBVA_DRIVER_NAME", "nvidia")
hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "wayland")
hl.env("XCURSOR_SIZE", 24)
hl.env("XCURSOR_THEME", "Skyrim")
hl.env("HYPRCURSOR_SIZE", 24)
